### ISSUE TITLE
Task 1: Create the Azure Migrate project

### ISSUE THREAD

**Issue by justinjakowski** [Microsoft/MCW-Azure-Migration#5]
In task one, we should make note that this should be done from the Hyper-V host in Azure after RDP'ing in.

**Comment by jtuliani** [comment]
There's no need to do this from the Hyper-V host. The Azure portal can be used from anywhere. It's easiest to use it from your local machine.

There's a case for using the Hyper-V host so that you can use portal link to download the Azure Migrate appliance. However, that's not needed in this case since the appliance is downloaded and unzipped for you by the lab provisioning scripts (which saves lots of time).

So, I don't think any change is required in this case.
