### ISSUE TITLE
Form for Azure Migrate Private Preview

### ISSUE THREAD

**Issue by cassiejones444** [Microsoft/MCW-Azure-Migration#7]
Hi, the form for accessing the Azure Migrate Private Preview has a mistake in it. Question 6 is for VMware machines, but asks not applicable for Hyper-V hosts.

![mcw azure migrate](https://user-images.githubusercontent.com/47842107/56780095-4c9bd000-6821-11e9-9d87-c180a734f51f.PNG)

Thanks
Cassie

**Comment by jtuliani** [comment]
The Azure Migrate v2 preview adds both Hyper-V assessment and VMware migration to the Azure Migrate service. That's why the on-boarding form to access the preview asks about both Hyper-V and VMware.

Also, this form is outside our control. It's owned by the product group.

So, there's no change required here, nor is any change possible as part of this MCW.

**Comment by cassiejones444** [comment]
The language is for Hyper-v and should be that. Being picky but it just shows someone isn’t paying attention. There are other questions that relate to VMware and are correct.

Who is the contact for the PG? I’ll take it up direct with them.

CJ.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
